<?php

namespace doc\MotoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends EntityRepository
{
	
	public function getAnnoncesCompatibles($id)
	{
		$query = $this->_em->createQuery('SELECT a FROM docMotoBundle:Annonce a JOIN a.genres_voulus g WHERE g.nom = :genre');
		$query->setParameter('genre', 'Roadster');
		
		
		$results = $query->getResult();

		return $results;
	}
	
}
