<?php

namespace doc\MotoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotoRepository extends EntityRepository
{
	
	public function getModelesByMarque($id)
    {
		return $this
		  ->createQueryBuilder('a')
		  ->where('a.marque = '.$id)
		;
    }
	
}
